### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "teste@teste9.br",
  "password": "123456"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "teste@teste5.br",
  "password": "123456"
}

### Sign out as an existing user
POST http://localhost:3000/auth/signout

### Get the current user
GET http://localhost:3000/whoami

### Get user by id
GET http://localhost:3000/users/4

### Find all users with a given email
GET http://localhost:3000/users?email=teste@teste2.br

### Delete a user with a given id
DELETE http://localhost:3000/users/9